### ISSUE TITLE
System.MissingMethodException running on .NET Core 3.0

### ISSUE THREAD

**Issue by JonathonReinhart** [dsbenghe/Novell.Directory.Ldap.NETStandard#100]
I'm hacking on v4.2.1 of https://github.com/unosquare/passcore/ and seeing this error:
```
      Failed to update password
System.TypeInitializationException: The type initializer for 'Novell.Directory.Ldap.Logger' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.DebugLoggerFactoryExtensions.AddDebug(Microsoft.Extensions.Logging.ILoggerFactory)'.
   --- End of inner exception stack trace ---
   at Novell.Directory.Ldap.Logger.LogWarning(ILogger logger, String message, Exception ex)
   at Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider.PerformPasswordChange(String username, String currentPassword, String newPassword) in /build/src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs:line 127
   at Unosquare.PassCore.Web.Controllers.PasswordController.Post(ChangePasswordModel model) in /build/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs:line 119
```

Here's the code in `passcore`:
https://github.com/unosquare/passcore/blob/4.2.1/src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs#L127

It seems to be pointing here in `Novell.Directory.Ldap.NETStandard`:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/5d1256336a6d996aa7a8ea54e8ebe7d6bdeb58ad/src/Novell.Directory.Ldap.NETStandard/Logger.cs#L27

...but I'm not seeing any references to `Microsoft.Extensions.Logging.ILoggerFactory Microsoft.Extensions.Logging.DebugLoggerFactoryExtensions.AddDebug(Microsoft.Extensions.Logging.ILoggerFactory)`.

**Comment by DanielBretzigheimer** [comment]
The Problem is the following line:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/5d1256336a6d996aa7a8ea54e8ebe7d6bdeb58ad/src/Novell.Directory.Ldap.NETStandard/Logger.cs#L12

In .NET Core 3 the DebugLoggerFactoryExtensions no longer apply to a ILoggerFactory, but to the ILoggingBuilder interface. See documentation [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.debugloggerfactoryextensions.adddebug?view=dotnet-plat-ext-3.0#Microsoft_Extensions_Logging_DebugLoggerFactoryExtensions_AddDebug_Microsoft_Extensions_Logging_ILoggingBuilder_).

**Comment by dsbenghe** [comment]
Got rid of Microsoft.Extensions.Logging dependency from the library. I was planning anyway even before the report of this issue.
