### ISSUE TITLE
Why is RemoteCertificateNameMismatch server certificate validation suppressed by default?

### ISSUE THREAD

**Issue by linuxchata** [dsbenghe/Novell.Directory.Ldap.NETStandard#105]
According to https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/ef06c2f359e75be59f3963f59598a0ba3c7c5383/src/Novell.Directory.Ldap.NETStandard/Connection.cs#L481 by default the library ignores RemoteCertificateNameMismatch server certificate validation error.

Is it by design? It looks like severe security issue

**Comment by dsbenghe** [comment]
Of course, it is not by design - at least I think so.

Looked at the history and it seems that it was in the original source code from novell (https://www.microfocus.com/documentation/edirectory-developer-documentation/ldap-libraries-for-c-sharp/#) which I converted to net standard.

In fact, even the mono version (which is based on the same code from novell) has the same issue - https://github.com/mono/mono/blob/8150a38dae6fbf60a8a5ffc20a1d07b911fbc31b/mcs/class/Novell.Directory.Ldap/Novell.Directory.Ldap/Connection.cs#L665

I agree I don't see any reason for this default validation - really weird.

**Comment by linuxchata** [comment]
Resolving this issue as validation was fixed
