### ISSUE TITLE
ILdapConnection still not mockable and testable

### ISSUE THREAD

**Issue by matteo-mosca** [dsbenghe/Novell.Directory.Ldap.NETStandard#12]
Hi, I have found another problem that prevents testability of your library.

Types returned from methods in the `ILdapConnection` interface, such as `LdapResponseQueue` and others have only an internal constructor.

When creating a mock of `ILdapConnection` for testing purposes it's impossible to setup behaviour for such methods, as there's no way to construct the returned type.

I am willing to work on this and send you a pull request if you agree to fix this.

**Comment by dsbenghe** [comment]
I'm ok with the change; and generally I'm ok with any change in order to make easier to write tests when using the library (that was the point of the interface).

**Comment by pvaillant** [comment]
Wondering if this has gone anywhere? If no one is working on it, I'm happy to put some time into it as I need this as well.

**Comment by dsbenghe** [comment]
It doesn't seem that anyone is working on this ... so feel free to implement it.

**Comment by pvaillant** [comment]
My first pass seems to suggest that if we added constructors for the following, that would be the least disruptive way (as opposed to introducing interfaces for things which may require code changes/recompilation for people using the existing code):

 * LdapResponseQueue & LdapSearchQueue (both are subclasses of LdapMessageQueue which would require a non-internal constructor as well). Both implement merge in the same way, so I'm also not sure why either class really exists other than for semantic purposes.
 * LdapSearchResults (if we change the current constructor to public LdapSearchResults(ILdapConnection conn, ...) and LdapSearchQueue is made usable, that's probably enough)
 * LdapExtendedResponse (technically this one already has a public constructor but it takes RfcLdapMessage and that feels like a leaked implementation detail)

I'll give it a try and see if that's enough.

**Comment by pvaillant** [comment]
I feel like I just tugged a thread that's unraveling a sweater. LdapMessageQueue needs MessageAgent which is mostly ok, but has a sendMessage method that takes Connection which I'm loath to expose.

Looking at the way the code is written, would it make sense to refactor the Connection/MessageAgent/Message/MessageVector code into something more compact and testable? I guess maybe this is a large question that also involves #27 since that would likely also touch the same pieces. A related question would be, are the Queue based methods actually used or would they be used if async methods were available?

**Comment by dsbenghe** [comment]
I really doubt that anyone is using the queue based methods as the usage is tricky and requires quite a bit of knowledge about the internals to really use it correctly. I don't use them and they are in the interface just because are public methods in the implementation type - should not have been added there initially, anyway. So yeah, from my point of view we can remove all the queue based methods from the interface. The master branch has already a small public interface breaking change and the major version was changed to 3.

**Comment by mathewbergt** [comment]
+1
Currently trying to mock LdapSearchResults with much difficulty.

**Comment by Sebosek** [comment]
Can you share a sample where can I  see, how you were able to mock `LdapSearchResults`?

**Comment by nwoolls** [comment]
Would love to see an example of being able to mock `LdapSearchResults` - it doesn't seem possible currently with the `internal` constructor.

**Comment by dsbenghe** [comment]
This should be fine now. You can test with 3.0.0-beta3 and report if is still an issue.

**Comment by RyanGaudion** [comment]
`LdapConnection` has the method `Search` which takes 7 parameters and returns a `LdapSearchQueue` however `ILdapConnection` doesn't have this method. Is there any reason why this can't be added?
