### ISSUE TITLE
"No ciphers available" error after updating from .NET Core 3.1 to .NET 5 on Docker Linux

### ISSUE THREAD

**Issue by janex-PL** [dsbenghe/Novell.Directory.Ldap.NETStandard#165]
Up to this point, I've been using this package with no issue on ASP.NET Core app hosted in Docker container. I've been successfully connecting using this setup:

Code:
```csharp
  using var connection = new LdapConnection { SecureSocketLayer = true };
  connection.Connect(ldapPath, LdapConnection.DefaultSslPort);
  connection.Bind(userDomain, password);
```
Just a standard connection with SSL enabled
Dockerfile:
```Dockerfile
COPY ./certificates/*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates \
&& sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1.0/' /etc/ssl/openssl.cnf
```
Image used: `mcr.microsoft.com/dotnet/aspnet:5.0.4-buster-slim`
Here I'm copying certificates and updating them to container, then I'm changing TLS minimum version to TLSv1.0 since my AD server does not support higher versions.

As I've said, I was using this setup on .NET Core 3.1 with no issues, but when I updated project and container to use .NET 5, it started to throw an error when connecting to server:

`error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available`

I've tried changing my code to this and choose different protocols, but still nothing:
```csharp
var options = new LdapConnectionOptions().UseSsl().ConfigureSslProtocols(SslProtocols.Tls);

using var connection = new LdapConnection(options);
connection.Connect(ldapPath, LdapConnection.DefaultSslPort);
connection.Bind(userDomain, password);
```
I am not able to update AD server, so is there any fix/workaround to this issue?

**Comment by dsbenghe** [comment]
This looks to me like a container configuration issue. I would expect that you get the same error doing any sort of secure connection from your docker container i.e. don't use the library and try to connect via socket/SslStream.AuthenticateAsClientAsync to the secure port of the ldap server and you should get the same error.

Hopefully, you can find out what is your issue and share it with us. If you look in the list of closed issues there were plenty open related with ssl/certificates which were in fact due to usage/configuration.

**Comment by janex-PL** [comment]
Well, I found the solution...

Changing "TLSv1.0" to "TLSv1" in the Dockerfile was apparently everything I needed...

I want to die

**Comment by dsbenghe** [comment]
Thanks for posting the solution.
