### ISSUE TITLE
NetworkStream - ObjectDisposedException

### ISSUE THREAD

**Issue by Marfusios** [dsbenghe/Novell.Directory.Ldap.NETStandard#2]
Hello,

first of all, thank you for your work, it's great that somebody finally converted LDAP into .NET Core.

We got some strange issue while sending a lot of requests in short range of time. It looks like some kind of race condition. It throws unhandled ObjectDisposedException and kills whole application (ignoring try-catch block, without meaningful call stack). A reason is, that it is thrown on the other thread. 

I had to debug your code, switch to other threads and find out what's going on. There were 3 threads:

1. Main thread - just waiting in `Program.Main()`, `host.Run()` (asp.net, nothing interesting)
2. Stuck thread - stuck on line 1353 in class `Connection` - method `Stop()`, `this.enclosingInstance.reader.Join();`
3. Weird thread - call stack shows just `System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(...)` and nothing more

Full exception:
```
{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at Novell.Directory.Ldap.Asn1.Asn1Identifier..ctor(Stream in_Renamed) in C:\Users\CZ010158\Desktop\KM\External\Novell.Directory.Ldap.NETStandard\Novell.Directory.Ldap.NETStandard\Asn1\Asn1Identifier.cs:line 250
   at Novell.Directory.Ldap.Connection.ReaderThread.Run() in C:\Users\CZ010158\Desktop\KM\External\Novell.Directory.Ldap.NETStandard\Novell.Directory.Ldap.NETStandard\Connection.cs:line 1389
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)}
```

After debugging I've found out that exception is thrown on line 250 in class `Asn1Identifier` - constructor - `int r = in_Renamed.ReadByte();`

Pull request: #3 
We've fixed it by checking if the stream is already disposed and then ignore it. Don't know if it is the correct solution. Please review pull request.

**UPDATE**
It seems that it didn't help. It just reduced the number of crashes, but it still sometimes throws ObjectDisposedException (even when there is explicit try-catch block).
**Temporary workaround** is to have just one `LdapConnection` instance and use it in the whole application (all communication is synchronous).

@Sebosek
@marfusios

**Comment by dsbenghe** [comment]
Do you have a small repro so I can easy see the issue? - and I will try to fix it asap.
Are you sharing the LdapConnection between threads?

**Comment by dsbenghe** [comment]
Last weekend I wrote a repro (multiple threads running at the same time doing bind and add/remove ldap entry) and I could reproduce the issue.

The issue is due to the fact that the reader thread (which is reading data from the socket stream) is not guarding against the fact that the socket may be closed suddenly - and the exception can happen in multiple places in Run method. The issue is happening also in the old Novell library on .NET framework (strange that it survived for more than 10 years without anyone fixing it). 

Anyway, I fixed the issue; fixed also another issue (which again is also in the old .NET framework library) I found while running my repro - a race condition happening on disconnect, which was causing an exception on the main thread; stress tested these changes over 2 days with 50 threads against OpenDJ with no exception thrown - so yeah I think is fixed. New nuget package version 2.3.3 was released Friday.

Thanks for raising the issue.

**Comment by Marfusios** [comment]
Thank you for your great work. I will try it in our project next sprint. 
And sorry for not helping you, I couldn't find time to do small repro.

**Comment by uastephen45** [comment]
If i was looking to reproduce this issue on V2.2.1.0 of Novell.Directory.Ldap.dll what would i have to do? I want to ensure this is the issue i'm having before making any changes/upgrading.

**Comment by khannapk** [comment]
found this exact same issue when working with .NETStandard library version 2.3.0 . This issue occurs when your method processing the request is flooded with lot of requests in a small period of time. Will try out the 2.3.3 and let you know how it goes. Thanks for the fix

**Comment by dsbenghe** [comment]
why are you using such an old version of the library?
