### ISSUE TITLE
Modifying SearchConstraints

### ISSUE THREAD

**Issue by saschakloeppner** [dsbenghe/Novell.Directory.Ldap.NETStandard#5]
You are not able to change to SearchConstaints in a regular way, because the LdapConnection.SearchConstraints returns a clone of LdapConnection.Constraints.
To change the properties you have to get a clone, modify it and set these object as new value for LdapConnection.Constraints.

```
var contraints = ldapConnection.SearchConstraints;
contraints.MaxResults = 0;
ldapConnection.Constraints = contraints;
```

**Comment by dsbenghe** [comment]
By looking at the code & comments, the cloning is there by design: to maintain a consistent value for the constraints - e.g. you set the whole thing in one go, not partially as the constraints can be in use by another thread. Now if this really can happen or not may be another discussion - and I don't think it worth the effort to discover it even if the usage of this may be a nuisance to some.

I'm really conservative with the changes I'm doing (If it ain't broke, don't fix it) especially when is about threading - as most of the bugs I fixed were threading issues.
